/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CliRouteImport } from './routes/cli'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as ConfigsIndexRouteImport } from './routes/configs/index'
import { Route as ConfigsIdRouteImport } from './routes/configs/$id'
import { Route as ConfigsNewRouteImport } from './routes/configs/new'
import { Route as ExtensionsIndexRouteImport } from './routes/extensions/index'
import { Route as ExtensionsIdRouteImport } from './routes/extensions/$id'
import { Route as ExtensionsNewRouteImport } from './routes/extensions/new'
import { Route as MarketplacesIndexRouteImport } from './routes/marketplaces/index'
import { Route as MarketplacesIdRouteImport } from './routes/marketplaces/$id'
import { Route as MarketplacesNewRouteImport } from './routes/marketplaces/new'
import { Route as McpInfoRouteImport } from './routes/mcp.info'
import { Route as OnboardingAiPilotTeamsRouteImport } from './routes/onboarding/ai-pilot-teams'
import { Route as OnboardingMultiToolOrgsRouteImport } from './routes/onboarding/multi-tool-orgs'
import { Route as OnboardingNoCodeBuildersRouteImport } from './routes/onboarding/no-code-builders'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SkillsIdRouteImport } from './routes/skills/$id'
import { Route as SkillsNewRouteImport } from './routes/skills/new'
import { Route as SlashCommandsConvertRouteImport } from './routes/slash-commands/convert'
import { Route as SubscriptionsFormRouteImport } from './routes/subscriptions/form'
import { Route as ConfigsIdEditRouteImport } from './routes/configs/$id.edit'
import { Route as ExtensionsIdEditRouteImport } from './routes/extensions/$id.edit'
import { Route as MarketplacesIdEditRouteImport } from './routes/marketplaces/$id.edit'
import { Route as PluginsExtensionIdFormatRouteImport } from './routes/plugins/$extensionId/$format'
import { Route as SkillsIdEditRouteImport } from './routes/skills/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigsIndexRoute = ConfigsIndexRouteImport.update({
  id: '/configs/',
  path: '/configs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigsIdRoute = ConfigsIdRouteImport.update({
  id: '/configs/$id',
  path: '/configs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigsNewRoute = ConfigsNewRouteImport.update({
  id: '/configs/new',
  path: '/configs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsIndexRoute = ExtensionsIndexRouteImport.update({
  id: '/extensions/',
  path: '/extensions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsIdRoute = ExtensionsIdRouteImport.update({
  id: '/extensions/$id',
  path: '/extensions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsNewRoute = ExtensionsNewRouteImport.update({
  id: '/extensions/new',
  path: '/extensions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacesIndexRoute = MarketplacesIndexRouteImport.update({
  id: '/marketplaces/',
  path: '/marketplaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacesIdRoute = MarketplacesIdRouteImport.update({
  id: '/marketplaces/$id',
  path: '/marketplaces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacesNewRoute = MarketplacesNewRouteImport.update({
  id: '/marketplaces/new',
  path: '/marketplaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const McpInfoRoute = McpInfoRouteImport.update({
  id: '/mcp/info',
  path: '/mcp/info',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAiPilotTeamsRoute = OnboardingAiPilotTeamsRouteImport.update({
  id: '/onboarding/ai-pilot-teams',
  path: '/onboarding/ai-pilot-teams',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMultiToolOrgsRoute = OnboardingMultiToolOrgsRouteImport.update({
  id: '/onboarding/multi-tool-orgs',
  path: '/onboarding/multi-tool-orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNoCodeBuildersRoute =
  OnboardingNoCodeBuildersRouteImport.update({
    id: '/onboarding/no-code-builders',
    path: '/onboarding/no-code-builders',
    getParentRoute: () => rootRouteImport,
  } as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIdRoute = SkillsIdRouteImport.update({
  id: '/skills/$id',
  path: '/skills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SlashCommandsConvertRoute = SlashCommandsConvertRouteImport.update({
  id: '/slash-commands/convert',
  path: '/slash-commands/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsFormRoute = SubscriptionsFormRouteImport.update({
  id: '/subscriptions/form',
  path: '/subscriptions/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigsIdEditRoute = ConfigsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ConfigsIdRoute,
} as any)
const ExtensionsIdEditRoute = ExtensionsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ExtensionsIdRoute,
} as any)
const MarketplacesIdEditRoute = MarketplacesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MarketplacesIdRoute,
} as any)
const PluginsExtensionIdFormatRoute =
  PluginsExtensionIdFormatRouteImport.update({
    id: '/plugins/$extensionId/$format',
    path: '/plugins/$extensionId/$format',
    getParentRoute: () => rootRouteImport,
  } as any)
const SkillsIdEditRoute = SkillsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SkillsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/profile': typeof ProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/configs/$id': typeof ConfigsIdRouteWithChildren
  '/configs/new': typeof ConfigsNewRoute
  '/extensions/$id': typeof ExtensionsIdRouteWithChildren
  '/extensions/new': typeof ExtensionsNewRoute
  '/marketplaces/$id': typeof MarketplacesIdRouteWithChildren
  '/marketplaces/new': typeof MarketplacesNewRoute
  '/mcp/info': typeof McpInfoRoute
  '/onboarding/ai-pilot-teams': typeof OnboardingAiPilotTeamsRoute
  '/onboarding/multi-tool-orgs': typeof OnboardingMultiToolOrgsRoute
  '/onboarding/no-code-builders': typeof OnboardingNoCodeBuildersRoute
  '/skills/$id': typeof SkillsIdRouteWithChildren
  '/skills/new': typeof SkillsNewRoute
  '/slash-commands/convert': typeof SlashCommandsConvertRoute
  '/subscriptions/form': typeof SubscriptionsFormRoute
  '/configs/': typeof ConfigsIndexRoute
  '/extensions/': typeof ExtensionsIndexRoute
  '/marketplaces/': typeof MarketplacesIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/configs/$id/edit': typeof ConfigsIdEditRoute
  '/extensions/$id/edit': typeof ExtensionsIdEditRoute
  '/marketplaces/$id/edit': typeof MarketplacesIdEditRoute
  '/plugins/$extensionId/$format': typeof PluginsExtensionIdFormatRoute
  '/skills/$id/edit': typeof SkillsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/profile': typeof ProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/configs/$id': typeof ConfigsIdRouteWithChildren
  '/configs/new': typeof ConfigsNewRoute
  '/extensions/$id': typeof ExtensionsIdRouteWithChildren
  '/extensions/new': typeof ExtensionsNewRoute
  '/marketplaces/$id': typeof MarketplacesIdRouteWithChildren
  '/marketplaces/new': typeof MarketplacesNewRoute
  '/mcp/info': typeof McpInfoRoute
  '/onboarding/ai-pilot-teams': typeof OnboardingAiPilotTeamsRoute
  '/onboarding/multi-tool-orgs': typeof OnboardingMultiToolOrgsRoute
  '/onboarding/no-code-builders': typeof OnboardingNoCodeBuildersRoute
  '/skills/$id': typeof SkillsIdRouteWithChildren
  '/skills/new': typeof SkillsNewRoute
  '/slash-commands/convert': typeof SlashCommandsConvertRoute
  '/subscriptions/form': typeof SubscriptionsFormRoute
  '/configs': typeof ConfigsIndexRoute
  '/extensions': typeof ExtensionsIndexRoute
  '/marketplaces': typeof MarketplacesIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/configs/$id/edit': typeof ConfigsIdEditRoute
  '/extensions/$id/edit': typeof ExtensionsIdEditRoute
  '/marketplaces/$id/edit': typeof MarketplacesIdEditRoute
  '/plugins/$extensionId/$format': typeof PluginsExtensionIdFormatRoute
  '/skills/$id/edit': typeof SkillsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/profile': typeof ProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/configs/$id': typeof ConfigsIdRouteWithChildren
  '/configs/new': typeof ConfigsNewRoute
  '/extensions/$id': typeof ExtensionsIdRouteWithChildren
  '/extensions/new': typeof ExtensionsNewRoute
  '/marketplaces/$id': typeof MarketplacesIdRouteWithChildren
  '/marketplaces/new': typeof MarketplacesNewRoute
  '/mcp/info': typeof McpInfoRoute
  '/onboarding/ai-pilot-teams': typeof OnboardingAiPilotTeamsRoute
  '/onboarding/multi-tool-orgs': typeof OnboardingMultiToolOrgsRoute
  '/onboarding/no-code-builders': typeof OnboardingNoCodeBuildersRoute
  '/skills/$id': typeof SkillsIdRouteWithChildren
  '/skills/new': typeof SkillsNewRoute
  '/slash-commands/convert': typeof SlashCommandsConvertRoute
  '/subscriptions/form': typeof SubscriptionsFormRoute
  '/configs/': typeof ConfigsIndexRoute
  '/extensions/': typeof ExtensionsIndexRoute
  '/marketplaces/': typeof MarketplacesIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/configs/$id/edit': typeof ConfigsIdEditRoute
  '/extensions/$id/edit': typeof ExtensionsIdEditRoute
  '/marketplaces/$id/edit': typeof MarketplacesIdEditRoute
  '/plugins/$extensionId/$format': typeof PluginsExtensionIdFormatRoute
  '/skills/$id/edit': typeof SkillsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli'
    | '/profile'
    | '/auth/login'
    | '/auth/logout'
    | '/configs/$id'
    | '/configs/new'
    | '/extensions/$id'
    | '/extensions/new'
    | '/marketplaces/$id'
    | '/marketplaces/new'
    | '/mcp/info'
    | '/onboarding/ai-pilot-teams'
    | '/onboarding/multi-tool-orgs'
    | '/onboarding/no-code-builders'
    | '/skills/$id'
    | '/skills/new'
    | '/slash-commands/convert'
    | '/subscriptions/form'
    | '/configs/'
    | '/extensions/'
    | '/marketplaces/'
    | '/skills/'
    | '/configs/$id/edit'
    | '/extensions/$id/edit'
    | '/marketplaces/$id/edit'
    | '/plugins/$extensionId/$format'
    | '/skills/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli'
    | '/profile'
    | '/auth/login'
    | '/auth/logout'
    | '/configs/$id'
    | '/configs/new'
    | '/extensions/$id'
    | '/extensions/new'
    | '/marketplaces/$id'
    | '/marketplaces/new'
    | '/mcp/info'
    | '/onboarding/ai-pilot-teams'
    | '/onboarding/multi-tool-orgs'
    | '/onboarding/no-code-builders'
    | '/skills/$id'
    | '/skills/new'
    | '/slash-commands/convert'
    | '/subscriptions/form'
    | '/configs'
    | '/extensions'
    | '/marketplaces'
    | '/skills'
    | '/configs/$id/edit'
    | '/extensions/$id/edit'
    | '/marketplaces/$id/edit'
    | '/plugins/$extensionId/$format'
    | '/skills/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/cli'
    | '/profile'
    | '/auth/login'
    | '/auth/logout'
    | '/configs/$id'
    | '/configs/new'
    | '/extensions/$id'
    | '/extensions/new'
    | '/marketplaces/$id'
    | '/marketplaces/new'
    | '/mcp/info'
    | '/onboarding/ai-pilot-teams'
    | '/onboarding/multi-tool-orgs'
    | '/onboarding/no-code-builders'
    | '/skills/$id'
    | '/skills/new'
    | '/slash-commands/convert'
    | '/subscriptions/form'
    | '/configs/'
    | '/extensions/'
    | '/marketplaces/'
    | '/skills/'
    | '/configs/$id/edit'
    | '/extensions/$id/edit'
    | '/marketplaces/$id/edit'
    | '/plugins/$extensionId/$format'
    | '/skills/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliRoute: typeof CliRoute
  ProfileRoute: typeof ProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ConfigsIdRoute: typeof ConfigsIdRouteWithChildren
  ConfigsNewRoute: typeof ConfigsNewRoute
  ExtensionsIdRoute: typeof ExtensionsIdRouteWithChildren
  ExtensionsNewRoute: typeof ExtensionsNewRoute
  MarketplacesIdRoute: typeof MarketplacesIdRouteWithChildren
  MarketplacesNewRoute: typeof MarketplacesNewRoute
  McpInfoRoute: typeof McpInfoRoute
  OnboardingAiPilotTeamsRoute: typeof OnboardingAiPilotTeamsRoute
  OnboardingMultiToolOrgsRoute: typeof OnboardingMultiToolOrgsRoute
  OnboardingNoCodeBuildersRoute: typeof OnboardingNoCodeBuildersRoute
  SkillsIdRoute: typeof SkillsIdRouteWithChildren
  SkillsNewRoute: typeof SkillsNewRoute
  SlashCommandsConvertRoute: typeof SlashCommandsConvertRoute
  SubscriptionsFormRoute: typeof SubscriptionsFormRoute
  ConfigsIndexRoute: typeof ConfigsIndexRoute
  ExtensionsIndexRoute: typeof ExtensionsIndexRoute
  MarketplacesIndexRoute: typeof MarketplacesIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  PluginsExtensionIdFormatRoute: typeof PluginsExtensionIdFormatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configs/': {
      id: '/configs/'
      path: '/configs'
      fullPath: '/configs/'
      preLoaderRoute: typeof ConfigsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configs/$id': {
      id: '/configs/$id'
      path: '/configs/$id'
      fullPath: '/configs/$id'
      preLoaderRoute: typeof ConfigsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configs/new': {
      id: '/configs/new'
      path: '/configs/new'
      fullPath: '/configs/new'
      preLoaderRoute: typeof ConfigsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/': {
      id: '/extensions/'
      path: '/extensions'
      fullPath: '/extensions/'
      preLoaderRoute: typeof ExtensionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/$id': {
      id: '/extensions/$id'
      path: '/extensions/$id'
      fullPath: '/extensions/$id'
      preLoaderRoute: typeof ExtensionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/new': {
      id: '/extensions/new'
      path: '/extensions/new'
      fullPath: '/extensions/new'
      preLoaderRoute: typeof ExtensionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplaces/': {
      id: '/marketplaces/'
      path: '/marketplaces'
      fullPath: '/marketplaces/'
      preLoaderRoute: typeof MarketplacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplaces/$id': {
      id: '/marketplaces/$id'
      path: '/marketplaces/$id'
      fullPath: '/marketplaces/$id'
      preLoaderRoute: typeof MarketplacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplaces/new': {
      id: '/marketplaces/new'
      path: '/marketplaces/new'
      fullPath: '/marketplaces/new'
      preLoaderRoute: typeof MarketplacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/info': {
      id: '/mcp/info'
      path: '/mcp/info'
      fullPath: '/mcp/info'
      preLoaderRoute: typeof McpInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/ai-pilot-teams': {
      id: '/onboarding/ai-pilot-teams'
      path: '/onboarding/ai-pilot-teams'
      fullPath: '/onboarding/ai-pilot-teams'
      preLoaderRoute: typeof OnboardingAiPilotTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/multi-tool-orgs': {
      id: '/onboarding/multi-tool-orgs'
      path: '/onboarding/multi-tool-orgs'
      fullPath: '/onboarding/multi-tool-orgs'
      preLoaderRoute: typeof OnboardingMultiToolOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/no-code-builders': {
      id: '/onboarding/no-code-builders'
      path: '/onboarding/no-code-builders'
      fullPath: '/onboarding/no-code-builders'
      preLoaderRoute: typeof OnboardingNoCodeBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$id': {
      id: '/skills/$id'
      path: '/skills/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof SkillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slash-commands/convert': {
      id: '/slash-commands/convert'
      path: '/slash-commands/convert'
      fullPath: '/slash-commands/convert'
      preLoaderRoute: typeof SlashCommandsConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/form': {
      id: '/subscriptions/form'
      path: '/subscriptions/form'
      fullPath: '/subscriptions/form'
      preLoaderRoute: typeof SubscriptionsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configs/$id/edit': {
      id: '/configs/$id/edit'
      path: '/edit'
      fullPath: '/configs/$id/edit'
      preLoaderRoute: typeof ConfigsIdEditRouteImport
      parentRoute: typeof ConfigsIdRoute
    }
    '/extensions/$id/edit': {
      id: '/extensions/$id/edit'
      path: '/edit'
      fullPath: '/extensions/$id/edit'
      preLoaderRoute: typeof ExtensionsIdEditRouteImport
      parentRoute: typeof ExtensionsIdRoute
    }
    '/marketplaces/$id/edit': {
      id: '/marketplaces/$id/edit'
      path: '/edit'
      fullPath: '/marketplaces/$id/edit'
      preLoaderRoute: typeof MarketplacesIdEditRouteImport
      parentRoute: typeof MarketplacesIdRoute
    }
    '/plugins/$extensionId/$format': {
      id: '/plugins/$extensionId/$format'
      path: '/plugins/$extensionId/$format'
      fullPath: '/plugins/$extensionId/$format'
      preLoaderRoute: typeof PluginsExtensionIdFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$id/edit': {
      id: '/skills/$id/edit'
      path: '/edit'
      fullPath: '/skills/$id/edit'
      preLoaderRoute: typeof SkillsIdEditRouteImport
      parentRoute: typeof SkillsIdRoute
    }
  }
}

interface ConfigsIdRouteChildren {
  ConfigsIdEditRoute: typeof ConfigsIdEditRoute
}

const ConfigsIdRouteChildren: ConfigsIdRouteChildren = {
  ConfigsIdEditRoute: ConfigsIdEditRoute,
}

const ConfigsIdRouteWithChildren = ConfigsIdRoute._addFileChildren(
  ConfigsIdRouteChildren,
)

interface ExtensionsIdRouteChildren {
  ExtensionsIdEditRoute: typeof ExtensionsIdEditRoute
}

const ExtensionsIdRouteChildren: ExtensionsIdRouteChildren = {
  ExtensionsIdEditRoute: ExtensionsIdEditRoute,
}

const ExtensionsIdRouteWithChildren = ExtensionsIdRoute._addFileChildren(
  ExtensionsIdRouteChildren,
)

interface MarketplacesIdRouteChildren {
  MarketplacesIdEditRoute: typeof MarketplacesIdEditRoute
}

const MarketplacesIdRouteChildren: MarketplacesIdRouteChildren = {
  MarketplacesIdEditRoute: MarketplacesIdEditRoute,
}

const MarketplacesIdRouteWithChildren = MarketplacesIdRoute._addFileChildren(
  MarketplacesIdRouteChildren,
)

interface SkillsIdRouteChildren {
  SkillsIdEditRoute: typeof SkillsIdEditRoute
}

const SkillsIdRouteChildren: SkillsIdRouteChildren = {
  SkillsIdEditRoute: SkillsIdEditRoute,
}

const SkillsIdRouteWithChildren = SkillsIdRoute._addFileChildren(
  SkillsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliRoute: CliRoute,
  ProfileRoute: ProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ConfigsIdRoute: ConfigsIdRouteWithChildren,
  ConfigsNewRoute: ConfigsNewRoute,
  ExtensionsIdRoute: ExtensionsIdRouteWithChildren,
  ExtensionsNewRoute: ExtensionsNewRoute,
  MarketplacesIdRoute: MarketplacesIdRouteWithChildren,
  MarketplacesNewRoute: MarketplacesNewRoute,
  McpInfoRoute: McpInfoRoute,
  OnboardingAiPilotTeamsRoute: OnboardingAiPilotTeamsRoute,
  OnboardingMultiToolOrgsRoute: OnboardingMultiToolOrgsRoute,
  OnboardingNoCodeBuildersRoute: OnboardingNoCodeBuildersRoute,
  SkillsIdRoute: SkillsIdRouteWithChildren,
  SkillsNewRoute: SkillsNewRoute,
  SlashCommandsConvertRoute: SlashCommandsConvertRoute,
  SubscriptionsFormRoute: SubscriptionsFormRoute,
  ConfigsIndexRoute: ConfigsIndexRoute,
  ExtensionsIndexRoute: ExtensionsIndexRoute,
  MarketplacesIndexRoute: MarketplacesIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  PluginsExtensionIdFormatRoute: PluginsExtensionIdFormatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
